pipeline:
  build:
    image: node
    commands:
      - npm install
      - npm run build
  deploy:
    image: appleboy/drone-scp
    settings:
      host:
        from_secret: host
      key:
        from_secret: key
      user:
        from_secret: user
      source: ./dist/*
      target: /var/www/digipom/
      strip_components: 1